name: Deploy Next.js

on:
  push:
    branches:
      - main # adjust if you deploy from another branch

jobs:
  deploy-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Next.js to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/nextjs-build
            git pull origin main
            sudo docker-compose build nextjs
            sudo docker-compose up -d nextjs
